#!/bin/bash
#
# Test description
# This test is just a sanity test for a normal start.  The expected results
# are a master been promoted, slaves replicating from the master and VIPs 
# enabled.

# global include files
. config
. functions

testdir=`dirname $0`


#Called by other tests to get PRM up
setup() {

# start corosync
runcmd_all /etc/init.d/corosync start
sleep 20

# start pacemaker
runcmd_all /etc/init.d/pacemaker start
sleep 20

#load configuration

cat $testdir/base_config.crm | runcmd $SSH1 'cat - > /tmp/config.crm'
runcmd $SSH1 'crm configure load update /tmp/config.crm'

online_all

} 

runtest() {

build_assoc_uname_ssh
master=`check_master`
print_result check_master $?

check_slaves $master
print_result check_slave $?

check_VIPs -u $master
print_result check_VIPs $?

}

#Called by other test to get PRM down
cleanup() {
    standby_all
    sleep 20
    runcmd $SSH1 'crm configure erase'
}


# What kind of method was invoked?
case "$1" in
  setup)    setup;;
  runtest)  runtest;;
  cleanup)  cleanup;;

 *)     echo 'Non implemented'
        exit 1
esac












































































































































