#!/bin/bash
#
# Test description
# 
# Test a graceful failover between nodes

# global include files
. config
. functions

testdir=`dirname $0`


#Called by other tests to get PRM up
setup() {

./T01gracefulstart setup

} 

runtest() {

build_assoc_uname_ssh
master1=`check_master`

#Demote/promote
runcmd $SSH1 "crm node standby $master1"
sleep 10

master2=`check_master`
print_result "master switched from $master1 to $master2" $?

check_slaves $master2
print_result check_slave $?

check_VIPs -u $master2
print_result check_VIPs $?

# put the node back online
runcmd $SSH1 "crm node online $master1"

}

#Called by other test to get PRM down
cleanup() {

./T01gracefulstart cleanup    

}


# What kind of method was invoked?
case "$1" in
  setup)    setup;;
  runtest)  runtest;;
  cleanup)  cleanup;;

 *)     echo 'Non implemented'
        exit 1
esac












































































































































